"""Add extracted fields to paper

Revision ID: 163340041346
Revises: e761f8eda260
Create Date: 2026-04-14 16:54:42.177041

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '163340041346'
down_revision = 'e761f8eda260'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('methods', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('papers', sa.Column('limitations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('papers', sa.Column('claims', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'claims')
    op.drop_column('papers', 'limitations')
    op.drop_column('papers', 'methods')
    # ### end Alembic commands ###
