"""feedback

Revision ID: 8c9ac39e958d
Revises: 0003
Create Date: 2026-03-23 13:16:15.986124

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = '8c9ac39e958d'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('paper_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_registry_name'), 'dataset_registry', ['name'], unique=True)
    op.create_table('gaps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gap_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gap_description', sa.Text(), nullable=False),
    sa.Column('source_paper_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('top_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('paper_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('centroid_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('hypothesis_id', sa.Uuid(), nullable=False),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('lessons_learned', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('papers', sa.Column('cluster_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'papers', 'paper_clusters', ['cluster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'papers', type_='foreignkey')
    op.drop_column('papers', 'cluster_id')
    op.drop_table('experiment_results')
    op.drop_table('paper_clusters')
    op.drop_table('gaps')
    op.drop_index(op.f('ix_dataset_registry_name'), table_name='dataset_registry')
    op.drop_table('dataset_registry')
    # ### end Alembic commands ###
