"""Add debate transcript

Revision ID: aa8c715b5350
Revises: 163340041346
Create Date: 2026-04-14 17:06:45.302151

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa8c715b5350'
down_revision = '163340041346'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hypotheses', sa.Column('debate_transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hypotheses', 'debate_transcript')
    # ### end Alembic commands ###
