"""Add index

Revision ID: ce24b4289684
Revises: aa8c715b5350
Create Date: 2026-04-14 19:39:29.322788

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ce24b4289684'
down_revision = 'aa8c715b5350'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_index(op.f('ix_gaps_used'), 'gaps', ['used'], unique=False)
    op.create_index(op.f('ix_hypotheses_status'), 'hypotheses', ['status'], unique=False)
    op.create_index(op.f('ix_papers_arxiv_status'), 'papers', ['arxiv_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_papers_arxiv_status'), table_name='papers')
    op.drop_index(op.f('ix_hypotheses_status'), table_name='hypotheses')
    op.drop_index(op.f('ix_gaps_used'), table_name='gaps')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    # ### end Alembic commands ###
