"""feedback_v2

Revision ID: e761f8eda260
Revises: 8c9ac39e958d
Create Date: 2026-03-23 14:02:27.576564

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e761f8eda260'
down_revision = '8c9ac39e958d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_registry', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('gaps', sa.Column('cluster_id', sa.Uuid(), nullable=True))
    op.add_column('gaps', sa.Column('used', sa.Boolean(), server_default='false', nullable=False))
    op.create_foreign_key(None, 'gaps', 'paper_clusters', ['cluster_id'], ['id'])
    op.add_column('hypotheses', sa.Column('parent_hypothesis_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hypotheses', 'parent_hypothesis_id')
    op.drop_constraint(None, 'gaps', type_='foreignkey')
    op.drop_column('gaps', 'used')
    op.drop_column('gaps', 'cluster_id')
    op.drop_column('dataset_registry', 'updated_at')
    # ### end Alembic commands ###
